In [1]:
import pandas as pd
import numpy as np
from collections import Counter

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import preprocessing

from sklearn.utils import shuffle
# from sklearn.model_selection import train_test_split
# from sklearn.model_selection import LeaveOneOut
#methods
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
# parameters tuening
from sklearn.model_selection import GridSearchCV 
#metrics
from sklearn import metrics

from scipy.stats import sem, t
from scipy import mean

#Oversampling
# from imblearn.over_sampling import RandomOverSampler
from kmeans_smote import KMeansSMOTE


### multiprocessing
from multiprocessing.pool import Pool


In [2]:
data = pd.read_csv('prepared Data.csv')
print(data.shape)
data.head()


(922, 33)


gender  age    SBP        BMI  etiology of CKD    Hb  Alb    Cr       eGFR  \
0       2   74  120.0  23.137669                2  12.0  4.0  1.20  89.981926   
1       1   57  139.0  28.515625                2  15.9  4.8  0.84  88.330020   
2       1   32  154.0  24.582701                4  14.4  4.4  0.87  86.973875   
3       1   60  144.0  30.737407                2  14.4  4.7  2.22  86.874201   
4       1   49  135.0  23.758726                2  17.0  4.1  1.39  86.782629   

   CKD_stage  ...   eGFR(6M)  eGFR(12M)  eGFR(18M)  eGFR(24M)  eGFR(30M)  \
0          3  ...  26.454698  24.331582  24.682189  21.614854  20.420524   
1          2  ...  78.287758  71.343858  72.845992  71.908942  71.562914   
2          2  ...  75.027238  69.595257  68.856399  72.901926  69.749275   
3          4  ...  26.885061  24.917353  28.581660  29.237135  25.556002   
4          3  ...  46.978867  45.829455  41.488436  41.801561  38.106104   

   eGFR(36M)  eGFR(last visit)  average_obs  obsevasion_ duration  fclass  
0  20.420524         18.495328    25.275139                    37       0  
1  67.225032         67.225032    72.392152                    37       0  
2  69.171408         69.171408    72.694258                    36       0  
3  25.183703         25.183703    26.485251                    35       0  
4  38.106104         38.106104    43.081581                    30       0  

[5 rows x 33 columns]

In [3]:
col = data.columns

In [4]:
count = Counter(data['fclass'])
count


Counter({0: 611, 1: 170, 5: 51, 2: 42, 6: 48})

In [24]:
CL = SVC(kernel='linear',gamma='scale',class_weight='balanced', C=8.0)
model = CL.fit(data.values[:,:-1], data.values[:,-1])
# model.predict(data.values[100:120,:-1])
predict = model.predict(data.values[100:120,:-1])

cnf_matrix = metrics.confusion_matrix(data.values[100:120,-1], predict)
# print(method)
print(cnf_matrix)

[[10  0  2  1]
 [ 0  3  0  0]
 [ 0  0  0  0]
 [ 0  0  1  3]]


In [ ]:
from sklearn.model_selection import GridSearchCV 
  
# defining parameter range 
param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'kernel': ['poly','rbf','sigmoid','linear']}  
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3) 
  
# fitting the model for grid search 
grid.fit(data.values[:,:-1], data.values[:,-1]) 

/home/amin/.local/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2052: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] C=0.1, gamma=1, kernel=poly .....................................
[CV]  C=0.1, gamma=1, kernel=poly, score=0.5551948051948052, total=   1.8s
[CV] C=0.1, gamma=1, kernel=poly .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=poly, score=0.737012987012987, total=   1.2s
[CV] C=0.1, gamma=1, kernel=poly .....................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    2.9s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=poly, score=0.7287581699346405, total=   2.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6623376623376623, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6623376623376623, total=   0.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.6633986928104575, total=   0.1s
[CV] C=0.1, gamma=1, kernel=sigmoid ..................................
[CV]  C=0.1, gamma=1, kernel=sigmoid, score=0.6623376623376623, total=   0.0s
[CV] C=0.1, gamma=1, kernel=sigmoid ..................................
[CV]  C=0.1, gamma=1, kernel=sigmoid, score=0.6623376623376623, total=   0.0s
[CV] C=0.1, gamma=1, kernel=sigmoid ..................................
[CV]  C=0.1, gamma=1, kernel=sigmoid, score=0.6633986928104575, total=   0.0s
[CV] C=0.1, gamma=1, kernel=linear ........

[CV]  C=0.1, gamma=0.0001, kernel=linear, score=0.7987012987012987, total=   3.9s
[CV] C=0.1, gamma=0.0001, kernel=linear ..............................
[CV]  C=0.1, gamma=0.0001, kernel=linear, score=0.8051948051948052, total=   4.5s
[CV] C=0.1, gamma=0.0001, kernel=linear ..............................
[CV]  C=0.1, gamma=0.0001, kernel=linear, score=0.8006535947712419, total=   2.2s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV]  C=1, gamma=1, kernel=poly, score=0.5551948051948052, total=   2.1s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV]  C=1, gamma=1, kernel=poly, score=0.737012987012987, total=   1.3s
[CV] C=1, gamma=1, kernel=poly .......................................
[CV]  C=1, gamma=1, kernel=poly, score=0.7287581699346405, total=   2.2s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV]  C=1, gamma=1, kernel=rbf, score=0.6623376623376623, total=   0.1s
[CV] C=1, gamma=1, kernel=rbf ........

[CV]  C=1, gamma=0.0001, kernel=sigmoid, score=0.6623376623376623, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=sigmoid ...............................
[CV]  C=1, gamma=0.0001, kernel=sigmoid, score=0.6633986928104575, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=linear ................................
[CV]  C=1, gamma=0.0001, kernel=linear, score=0.801948051948052, total=  10.9s
[CV] C=1, gamma=0.0001, kernel=linear ................................


# Oversampling

In [5]:


# X, y = data.values[:int(800),:-1], data.values[:int(800),-1]
# [print('Class {} has {} instances'.format(label, count))
#  for label, count in zip(*np.unique(y, return_counts=True))]

# kmeans_smote = KMeansSMOTE(
#     kmeans_args={
#         'n_clusters': 400
#     },
#     smote_args={
#         'k_neighbors': 5
#     }
# )
# X_resampled, y_resampled = kmeans_smote.fit_sample(X, y)

# [print('Class {} has {} instances after oversampling'.format(label, count))
#  for label, count in zip(*np.unique(y_resampled, return_counts=True))]
# print(Counter(y_resampled))

In [6]:
# define oversampling strategy
# oversample = RandomOverSampler(sampling_strategy='minority')

## Below code works for binary classification 
# oversample = RandomOverSampler(sampling_strategy=0.5)

In [7]:

# # define oversampling strategy
# oversample = RandomOverSampler(sampling_strategy='minority')

# # fit and apply the transform
# X_over, y_over = oversample.fit_resample(data.values[:,:-1], data.values[:,-1])

# Max = dict(Counter(y_over))[0.0]
# flag = True
# while flag:
#     X_over, y_over = oversample.fit_resample(X_over, y_over)
#     for x in list(dict(Counter(y_over)).values()):
#         if x == Max:
#             flag = False
#         else:
#             flag = True
#             break
        
# # summarize class distribution
# print(Counter(y_over))

In [9]:
# adict = dict()
# adict.update(zip(d.columns,col[:-1]))
# adict

In [10]:
# d = pd.DataFrame(X_over)
# adict = dict()
# adict.update(zip(d.columns,col[:-1]))
# d.rename(columns = adict, inplace =True)
# d['fclass'] = y_over
# d.head()

In [11]:
# count = Counter(data['fclass'])
# count

Counter({0: 611, 1: 170, 5: 51, 2: 42, 6: 48})

In [12]:
# data = d.copy()

In [5]:
cat0 = shuffle(data[data['fclass']==0])
cat1 = shuffle(data[data['fclass']==1])
cat2 = shuffle(data[data['fclass']==2])
cat5 = shuffle(data[data['fclass']==5])
cat6 = shuffle(data[data['fclass']==6])


In [6]:

lenCat0 = len(cat0.iloc[:,0])
lenCat1 = len(cat1.iloc[:,0])
lenCat2 = len(cat2.iloc[:,0])
lenCat5 = len(cat5.iloc[:,0])
lenCat6 = len(cat6.iloc[:,0])


In [7]:
methodList = []
accRes = []
accConf = []
nFold = 10
# sensitivityList = []
# specificityList = []

In [8]:
methods = ['Logistic Regression', 'K Neighbors Classifier', 'Random Forest', 'Gaussian Naive Bayes',\
          'Support Vector Machine', 'Gradient Boosting', 'Linear Discriminant Analysis', 'Decision Tree',\
          'soft_VotingClassifier','hard_VotingClassifier']

In [9]:
## 10 fold-CV

def classifiers(method):
    if method == 'Logistic Regression':
        CL = LogisticRegression()
    if method == 'K Neighbors Classifier':
        CL = KNeighborsClassifier(n_neighbors=10)
    if method == 'Random Forest':
        CL = RandomForestClassifier(max_depth=35)
    if method == 'Gaussian Naive Bayes':
        CL = GaussianNB()
    if method == 'Linear Discriminant Analysis':
        CL = LinearDiscriminantAnalysis()
    if method == 'Decision Tree':
        CL = DecisionTreeClassifier()
    if method == 'Support Vector Machine':
        CL = SVC(kernel='linear',gamma='scale')
#         class_weight='balanced', C=1.0
    if method == 'Gradient Boosting':
        CL = GradientBoostingClassifier()
    if method == 'soft_VotingClassifier':
        cl1 = LogisticRegression()
        cl2 = KNeighborsClassifier(n_neighbors=10)
        cl3 = RandomForestClassifier(max_depth=35)
        cl4 = GaussianNB()
        cl5 = LinearDiscriminantAnalysis()
        cl6 = DecisionTreeClassifier()
        cl7 = SVC(kernel='linear',gamma='scale')
        cl8 = GradientBoostingClassifier()
        estimator = [(method[0],cl1), (method[1],cl2), (method[2],cl3), (method[3],cl4),\
                     (method[4],cl5), (method[5],cl6), (method[6],cl7), (method[7],cl8)]
        CL = VotingClassifier(estimators=estimator,
        voting='soft', weights=[5, 5, 10, 5, 6, 8, 4, 10])
        
    if method == 'hard_VotingClassifier':
        cl1 = LogisticRegression()
        cl2 = KNeighborsClassifier(n_neighbors=10)
        cl3 = RandomForestClassifier(max_depth=35)
        cl4 = GaussianNB()
        cl5 = LinearDiscriminantAnalysis()
        cl6 = DecisionTreeClassifier()
        cl7 = SVC(kernel='linear',gamma='scale')
        cl8 = GradientBoostingClassifier()
        estimator = [(method[0],cl1), (method[1],cl2), (method[2],cl3), (method[3],cl4),\
                     (method[4],cl5), (method[5],cl6), (method[6],cl7), (method[7],cl8)]
        CL = VotingClassifier(estimators=estimator, voting='hard')        
    print(type(CL))
    accList = []
    for j in range(nFold):

        i = j*.1
        k = (j+1)*.1
        #train
        X_train = cat0.iloc[int(k * lenCat0):,:-1].append(\
                  cat1.iloc[int(k * lenCat1):,:-1].append(\
                  cat2.iloc[int(k * lenCat2):,:-1].append(\
                  cat5.iloc[int(k * lenCat5):,:-1].append(\
                  cat6.iloc[int(k * lenCat6):,:-1].append(\
                  cat0.iloc[:int(i * lenCat0),:-1].append(\
                  cat1.iloc[:int(i * lenCat1),:-1].append(\
                  cat2.iloc[:int(i * lenCat2),:-1].append(\
                  cat5.iloc[:int(i * lenCat5),:-1].append(\
                  cat6.iloc[:int(i * lenCat6),:-1]                                       
                                                         )))))))))

        y_train = cat0.iloc[int(k * lenCat0):,-1].append(\
                  cat1.iloc[int(k * lenCat1):,-1].append(\
                  cat2.iloc[int(k * lenCat2):,-1].append(\
                  cat5.iloc[int(k * lenCat5):,-1].append(\
                  cat6.iloc[int(k * lenCat6):,-1].append(\
                  cat0.iloc[:int(i * lenCat0),-1].append(\
                  cat1.iloc[:int(i * lenCat1),-1].append(\
                  cat2.iloc[:int(i * lenCat2),-1].append(\
                  cat5.iloc[:int(i * lenCat5),-1].append(\
                  cat6.iloc[:int(i * lenCat6),-1]                                         
                                                        )))))))))
#         print(X_train.shape, y_train.shape)
    

        # fit and apply the Oversampling:
        #### Repeatitive oversampling
#         X_over, y_over = oversample.fit_resample(X_train, y_train)

#         Max = dict(Counter(y_over))[0.0]
#         flag = True
#         while flag:
#             X_over, y_over = oversample.fit_resample(X_over, y_over)
#             for x in list(dict(Counter(y_over)).values()):
#                 if x == Max:
#                     flag = False
#                 else:
#                     flag = True
#                     break
#         X_train, y_train = X_over.copy(), y_over.copy()
        # summarize class distribution
#         print(Counter(y_train))

#         print(X_train.shape, y_train.shape)
    

        # fit and apply the Oversampling:
        #### K-means oversampling
#         [print('Class {} has {} instances'.format(label, count))
#          for label, count in zip(*np.unique(y, return_counts=True))]

        kmeans_smote = KMeansSMOTE(
            kmeans_args={
                'n_clusters': int(dict(Counter(y_train))[0.0]*(1-1/nFold))
            },
            smote_args={
                'k_neighbors': 10
            }
        )
        X_train, y_train = kmeans_smote.fit_sample(X_train, y_train)

#         [print('Class {} has {} instances after oversampling'.format(label, count))
#          for label, count in zip(*np.unique(y_resampled, return_counts=True))]
        # summarize class distribution
#         print(Counter(y_train))

        #test
        X_test = cat0.iloc[int(i * lenCat0):int(k * lenCat0),:-1].append(\
                 cat1.iloc[int(i * lenCat1):int(k * lenCat1),:-1].append(\
                 cat2.iloc[int(i * lenCat2):int(k * lenCat2),:-1].append(\
                 cat5.iloc[int(i * lenCat5):int(k * lenCat5),:-1].append(\
                 cat6.iloc[int(i * lenCat6):int(k * lenCat6),:-1]))))

        y_test = cat0.iloc[int(i * lenCat0):int(k * lenCat0),-1].append(\
                 cat1.iloc[int(i * lenCat1):int(k * lenCat1),-1].append(\
                 cat2.iloc[int(i * lenCat2):int(k * lenCat2),-1].append(\
                 cat5.iloc[int(i * lenCat5):int(k * lenCat5),-1].append(\
                 cat6.iloc[int(i * lenCat6):int(k * lenCat6),-1]))))
#         print(X_test.shape, y_test.shape)
        #preprocessing
        scaler = preprocessing.StandardScaler().fit(X_train)
        X_train_transformed = scaler.transform(X_train)
        X_test_transformed = scaler.transform(X_test)
        
        model = CL.fit(X_train, np.array(list(y_train)))
        
        predict = np.array(model.predict(X_test))
        
        cnf_matrix = metrics.confusion_matrix(y_test, predict)
        print(method)
        print(cnf_matrix)
#         #matplotlib inline
#         class_names=[0,1] # name  of classes
#         fig, ax = plt.subplots()
#         tick_marks = np.arange(len(class_names))
#         plt.xticks(tick_marks, class_names)
#         plt.yticks(tick_marks, class_names)

#         # create heatmap
#         sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
#         ax.xaxis.set_label_position("top")
#         plt.tight_layout()
#         plt.title(method+ ' fold of '+str(j), y=1.1)

#         plt.ylabel('Actual label')
#         plt.xlabel('Predicted label')

#         plt.show()


        acc = metrics.accuracy_score(y_test.values, predict)
        accList.append(acc)


    methodList.append(method)
    confidence = 0.95

    naccList = len(accList)
    maccList = np.mean(accList)
    std_erraccList = sem(accList)
    haccList = std_erraccList * t.ppf((1 + confidence) / 2, naccList - 1)




    print("Accuracy:         "+ str(round(maccList,2)) + '  -+' + str(round(haccList,4)))
    accRes.append(round(maccList,2))
    accConf.append(round(haccList,4))
if __name__ == "__main__":
    p = Pool(processes=6)
    result = p.map(classifiers, methods)
    p.close()
    p.join()

<class 'sklearn.neighbors.classification.KNeighborsClassifier'><class 'sklearn.discriminant_analysis.LinearDiscriminantAnalysis'><class 'sklearn.ensemble.forest.RandomForestClassifier'><class 'sklearn.naive_bayes.GaussianNB'><class 'sklearn.tree.tree.DecisionTreeClassifier'><class 'sklearn.linear_model.logistic.LogisticRegression'>







/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[47  7  1  6  0]
 [ 1 12  0  2  2]
 [ 1  2  1  0  0]
 [ 3  2  0  0  0]
 [ 0  3  1  0  0]]
Logistic Regression
[[54  2  0  5  0]
 [ 1 13  0  1  2]
 [ 1  0  1  1  1]
 [ 4  1  0  0  0]
 [ 0  3  1  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gaussian Naive Bayes
[[51  8  0  2  0]
 [ 3 13  0  1  0]
 [ 2  2  0  0  0]
 [ 3  2  0  0  0]
 [ 0  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Random Forest
[[61  0  0  0  0]
 [ 2 15  0  0  0]
 [ 3  1  0  0  0]
 [ 4  1  0  0  0]
 [ 0  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[56  0  1  4  0]
 [ 1 11  0  2  3]
 [ 0  2  1  1  0]
 [ 2  1  1  1  0]
 [ 0  4  0  0  0]]
K Neighbors Classifier
[[54  6  0  0  1]
 [ 4 12  0  1  0]
 [ 1  2  0  0  1]
 [ 3  2  0  0  0]
 [ 1  3  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/amin/.local/lib/python3.

Linear Discriminant Analysis
[[53  2  0  3  3]
 [ 4  8  2  0  3]
 [ 2  0  1  0  1]
 [ 4  0  1  0  0]
 [ 0  2  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gaussian Naive Bayes
[[59  1  0  1  0]
 [ 4 13  0  0  0]
 [ 4  0  0  0  0]
 [ 5  0  0  0  0]
 [ 0  3  0  0  2]]
Logistic Regression
[[37  2  4 18  0]
 [ 0  9  4  2  2]
 [ 0  0  3  1  0]
 [ 2  0  2  1  0]
 [ 0  2  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[51  2  2  6  0]
 [ 3  8  1  3  2]
 [ 1  0  2  1  0]
 [ 4  0  1  0  0]
 [ 1  2  1  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[58  0  0  0  3]
 [ 6 11  0  0  0]
 [ 4  0  0  0  0]
 [ 5  0  0  0  0]
 [ 1  2  0  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Random Forest
[[57  0  0  4  0]
 [ 3 12  0  1  1]
 [ 3  0  1  0  0]
 [ 4  0  0  1  0]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Logistic Regression
[[53  0  2  5  1]
 [ 0 13  0  0  4]
 [ 1  0  2  1  0]
 [ 3  1  1  0  0]
 [ 0  3  0  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[55  0  3  1  2]
 [ 2 13  0  0  2]
 [ 4  0  0  0  0]
 [ 3  0  1  0  1]
 [ 0  2  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[55  1  0  3  2]
 [ 3 12  0  0  2]
 [ 3  0  0  0  1]
 [ 4  0  0  1  0]
 [ 1  3  0  0  1]]
Random Forest
[[57  1  0  1  2]
 [ 2 15  0  0  0]
 [ 3  0  0  1  0]
 [ 5  0  0  0  0]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gaussian Naive Bayes
[[52  8  0  1  0]
 [ 5 12  0  0  0]
 [ 4  0  0  0  0]
 [ 5  0  0  0  0]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[50  4  3  4  0]
 [ 2 13  0  1  1]
 [ 3  1  0  0  0]
 [ 4  0  0  1  0]
 [ 1  3  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[29  4 10 18  0]
 [ 0 10  1  0  6]
 [ 0  0  0  2  2]
 [ 2  0  0  2  1]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_lab

Gaussian Naive Bayes
[[30  6  7 18  0]
 [ 0  6  0  0 11]
 [ 0  1  2  0  1]
 [ 2  0  1  2  0]
 [ 1  1  1  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[33  1  6 18  3]
 [ 0 12  0  0  5]
 [ 0  1  1  1  1]
 [ 3  0  0  2  0]
 [ 0  3  2  0  0]]
Logistic Regression
[[40  4  6 11  0]
 [ 0  9  2  0  6]
 [ 0  1  0  2  1]
 [ 3  0  0  2  0]
 [ 0  3  1  0  1]]
Random Forest
[[52  3  5  1  0]
 [ 1 13  0  0  3]
 [ 1  1  0  1  1]
 [ 5  0  0  0  0]
 [ 1  3  1  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[48  1  3  7  2]
 [ 2 10  1  0  4]
 [ 1  0  1  1  1]
 [ 5  0  0  0  0]
 [ 1  3  0  1  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[47  2  4  5  3]
 [ 2  4  0  0 11]
 [ 2  1  0  0  2]
 [ 3  0  1  1  0]
 [ 0  3  1  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gaussian Naive Bayes
[[40  5  1 15  0]
 [ 2  4  0  0 11]
 [ 3  1  0  0  1]
 [ 3  0  1  1  0]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[53  3  0  4  1]
 [ 2 12  1  0  2]
 [ 3  1  1  0  0]
 [ 4  0  1  0  0]
 [ 1  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Random Forest
[[60  1  0  0  0]
 [ 2 13  1  0  1]
 [ 3  2  0  0  0]
 [ 5  0  0  0  0]
 [ 1  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Logistic Regression

/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.



[[32  5  5 19  0]
 [ 0 11  1  0  5]
 [ 2  1  1  0  1]
 [ 2  0  1  2  0]
 [ 0  3  1  0  1]]
Decision Tree
[[51  3  2  4  1]
 [ 1  9  2  0  5]
 [ 1  0  1  1  2]
 [ 4  0  1  0  0]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[33  1  6 18  3]
 [ 0  9  5  0  3]
 [ 0  1  2  1  0]
 [ 0  0  3  2  0]
 [ 0  3  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gaussian Naive Bayes
[[29  2  7 22  1]
 [ 0 13  0  1  3]
 [ 1  1  2  0  0]
 [ 1  0  2  2  0]
 [ 0  1  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[34  1  6 20  0]
 [ 1  9  1  1  5]
 [ 1  0  1  1  1]
 [ 2  0  0  3  0]
 [ 0  3  0  0  1]]
Random Forest
[[57  1  2  0  1]
 [ 3 11  2  0  1]
 [ 4  0  0  0  0]
 [ 5  0  0  0  0]
 [ 0  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[51  2  2  5  1]
 [ 2 10  1  0  4]
 [ 2  1  1  0  0]
 [ 4  0  1  0  0]
 [ 0  3  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Logistic Regression
[[55  3  3  0  0]
 [ 3 11  1  0  2]
 [ 1  0  3  0  0]
 [ 3  0  2  0  0]
 [ 0  3  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[38  5  3 11  4]
 [ 0 13  0  1  3]
 [ 1  0  1  1  1]
 [ 0  0  2  3  0]
 [ 0  4  1  0  0]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_lab

Gaussian Naive Bayes
[[29  1  1 27  3]
 [ 0  7  0  2  8]
 [ 2  1  1  0  0]
 [ 0  0  2  3  0]
 [ 0  2  0  1  2]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Random Forest
[[59  2  0  0  0]
 [ 0 13  0  0  4]
 [ 2  0  2  0  0]
 [ 4  0  1  0  0]
 [ 0  3  1  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[33  3  6 18  1]
 [ 0  9  0  1  7]
 [ 1  0  2  0  1]
 [ 2  0  2  1  0]
 [ 0  2  2  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[35  5  8 10  3]
 [ 0 10  3  1  3]
 [ 0  0  2  0  2]
 [ 1  0  1  3  0]
 [ 0  2  0  0  3]]
Decision Tree
[[54  4  0  3  0]
 [ 1 10  0  0  6]
 [ 2  0  1  0  1]
 [ 4  0  1  0  0]
 [ 0  2  1  0  2]]
Logistic Regression
[[41  2  4 14  0]
 [ 1 10  2  1  3]
 [ 1  0  2  0  1]
 [ 2  0  2  1  0]
 [ 0  2  1  1  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_lab

Gaussian Naive Bayes
[[25  4 11 19  2]
 [ 0 11  2  0  4]
 [ 0  1  3  0  0]
 [ 2  0  1  2  0]
 [ 0  2  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[29  6  6 18  2]
 [ 0  9  0  1  7]
 [ 0  0  3  0  1]
 [ 2  0  1  2  0]
 [ 0  3  0  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Random Forest
[[54  2  2  1  2]
 [ 1 14  0  0  2]
 [ 1  0  2  1  0]
 [ 4  0  1  0  0]
 [ 0  4  0  0  1]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 6. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[51  3  0  7  0]
 [ 1 13  1  0  2]
 [ 3  1  0  0  0]
 [ 4  0  1  0  0]
 [ 1  3  0  0  1]]
Linear Discriminant Analysis
[[37  3  4 13  4]
 [ 0  7  4  0  6]
 [ 1  0  2  0  1]
 [ 3  0  0  2  0]
 [ 0  3  0  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Logistic Regression
[[51  3  3  3  1]
 [ 1 10  1  3  2]
 [ 2  0  1  1  0]
 [ 3  0  0  2  0]
 [ 0  0  1  0  4]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 6. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_lab

Gaussian Naive Bayes
[[29  2 13 14  3]
 [ 4  2  1  0 10]
 [ 1  1  1  0  1]
 [ 1  0  1  3  0]
 [ 0  0  0  0  5]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 6. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


K Neighbors Classifier
[[37  0  6 14  4]
 [ 1  9  2  1  4]
 [ 0  1  1  1  1]
 [ 2  0  0  3  0]
 [ 0  1  1  0  3]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Random Forest
[[52  1  4  4  0]
 [ 3  8  1  1  4]
 [ 1  2  1  0  0]
 [ 5  0  0  0  0]
 [ 0  2  1  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[48  1  4  7  1]
 [ 3 10  0  1  3]
 [ 2  1  1  0  0]
 [ 5  0  0  0  0]
 [ 1  2  0  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Linear Discriminant Analysis
[[55  5  2  0  0]
 [ 2 11  2  0  2]
 [ 2  1  2  0  0]
 [ 5  1  0  0  0]
 [ 1  4  0  0  0]]
Accuracy:         0.61  -+0.071
<class 'sklearn.svm.classes.SVC'>


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Logistic Regression
[[44  0  5 11  1]
 [ 1 11  2  0  3]
 [ 0  1  2  1  0]
 [ 2  0  0  3  0]
 [ 0  1  1  0  3]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gaussian Naive Bayes
[[50  6  5  1  0]
 [ 5 12  0  0  0]
 [ 2  1  2  0  0]
 [ 6  0  0  0  0]
 [ 0  5  0  0  0]]
Accuracy:         0.57  -+0.0957
K Neighbors Classifier<class 'sklearn.ensemble.gradient_boosting.GradientBoostingClassifier'>

[[56  2  2  2  0]
 [ 3 14  0  0  0]
 [ 4  0  1  0  0]
 [ 5  0  1  0  0]
 [ 0  3  1  0  1]]
Accuracy:         0.63  -+0.0853


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Random Forest
[[60  1  1  0  0]
 [ 2 14  0  0  1]
 [ 4  1  0  0  0]
 [ 6  0  0  0  0]
 [ 0  5  0  0  0]]
Accuracy:         0.77  -+0.033


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Decision Tree
[[49  1  7  4  1]
 [ 0 11  1  0  5]
 [ 2  1  1  1  0]
 [ 6  0  0  0  0]
 [ 0  4  1  0  0]]
Accuracy:         0.69  -+0.027


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/amin/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWa

Logistic Regression
[[39  3  7 11  2]
 [ 0 10  1  0  6]
 [ 0  0  1  3  1]
 [ 3  0  1  2  0]
 [ 0  1  0  0  4]]
Accuracy:         0.65  -+0.0695


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[54  3  2  2  0]
 [ 3 13  0  1  0]
 [ 2  1  1  0  0]
 [ 4  1  0  0  0]
 [ 0  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Support Vector Machine
[[59  1  0  1  0]
 [ 3 11  1  0  2]
 [ 1  1  1  0  1]
 [ 4  1  0  0  0]
 [ 1  3  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[56  1  1  3  0]
 [ 4 11  1  0  1]
 [ 3  0  1  0  0]
 [ 5  0  0  0  0]
 [ 1  2  1  0  1]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[54  3  2  2  0]
 [ 2 12  1  0  2]
 [ 3  0  0  1  0]
 [ 3  1  0  1  0]
 [ 0  1  0  0  4]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Support Vector Machine
[[45  0  2 14  0]
 [ 3 11  1  1  1]
 [ 1  0  2  1  0]
 [ 4  0  0  1  0]
 [ 1  2  2  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[55  1  3  1  1]
 [ 1 11  0  0  5]
 [ 1  0  0  1  2]
 [ 5  0  0  0  0]
 [ 1  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[59  0  1  0  1]
 [ 0 13  1  0  3]
 [ 4  0  0  0  1]
 [ 4  0  1  0  0]
 [ 1  4  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[45  1  3 12  0]
 [ 0 13  0  0  4]
 [ 1  0  1  2  0]
 [ 3  1  1  0  0]
 [ 0  2  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[55  1  3  1  1]
 [ 3 10  1  0  3]
 [ 3  0  0  0  1]
 [ 3  0  1  1  0]
 [ 0  2  0  0  2]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[56  2  0  3  0]
 [ 2 11  0  0  4]
 [ 3  0  0  0  1]
 [ 2  0  2  1  0]
 [ 0  5  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Support Vector Machine
[[45  2  3 11  0]
 [ 0 12  1  0  4]
 [ 1  0  0  2  1]
 [ 3  0  0  2  0]
 [ 0  2  1  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[51  2  4  2  2]
 [ 2 10  2  0  3]
 [ 0  1  3  0  0]
 [ 3  0  1  1  0]
 [ 0  2  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 6. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Gradient Boosting
[[52  2  3  4  0]
 [ 4 11  0  0  2]
 [ 1  2  1  0  0]
 [ 5  0  0  0  0]
 [ 0  2  1  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[34  4  1 22  0]
 [ 2  8  1  1  5]
 [ 2  0  1  0  2]
 [ 2  0  0  3  0]
 [ 0  5  0  0  0]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))


Gradient Boosting
[[56  2  1  2  1]
 [ 3 12  0  0  2]
 [ 2  1  1  1  0]
 [ 6  0  0  0  0]
 [ 2  2  0  0  1]]
Accuracy:         0.74  -+0.0136


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[37  1  4 18  1]
 [ 0 10  2  0  5]
 [ 1  0  2  1  0]
 [ 1  0  2  2  0]
 [ 0  1  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 6. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[33  5  3 19  1]
 [ 2 12  1  1  1]
 [ 2  1  1  0  0]
 [ 1  0  2  2  0]
 [ 1  1  1  0  2]]


/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[52  2  5  0  2]
 [ 0 13  0  1  3]
 [ 2  0  1  1  0]
 [ 4  0  1  0  0]
 [ 1  1  0  0  3]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[40  0  2 18  1]
 [ 2 11  2  0  2]
 [ 0  2  1  1  0]
 [ 2  0  0  3  0]
 [ 0  1  2  0  2]]


/home/amin/.local/lib/python3.6/site-packages/kmeans_smote.py:322: UserWarning: No minority clusters found for class 5. Performing regular SMOTE. Try changing the number of clusters.
  warnings.warn('No minority clusters found for class {}. Performing regular SMOTE. Try changing the number of clusters.'.format(minority_class_label))
/home/amin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:137: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Support Vector Machine
[[39  2  3 17  1]
 [ 0 12  2  0  3]
 [ 1  0  2  0  2]
 [ 3  0  0  3  0]
 [ 1  2  0  0  2]]
Accuracy:         0.64  -+0.0618


UnboundLocalError: local variable 'CL' referenced before assignment

In [ ]:


# def calcNum(n):#some arbitrary, time-consuming calculation on a number
#   print "Calcs Started on ", n
#   m = n
#   for i in range(5000000):
#     m += i%25
#     if m > n*n:
#       m /= 2
#   return m

# if __name__ == "__main__":
#   p = Pool(processes=3)
# dict(Counter(data['fclass']))[0.0]*(1-1/nFold)

In [ ]:
result = []
result = pd.DataFrame(result)
result['Method'],result['Accuracy'],result['ACC CI'] = methodList,accRes,accConf
result.to_excel('kidney_Classification_Result.xlsx',index=False)
result